language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support
  licenses:
      - android-sdk-license-.+
      - '.+'

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew assembleDebug --daemon